-- Supabase PostgreSQL Table Schema for YolSinyali Traffic Reporting Application

-- 1. Create the reports table
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    report_type VARCHAR(50) NOT NULL, -- 'Trafik Çevirmesi', 'Kaza', 'Yemek Yeri'
    duration_minutes INTEGER NOT NULL, -- Duration in minutes: 120 (2h), 360 (6h), 720 (12h), 1440 (24h), 2880 (48h), or -1 (no duration / permanent)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 2. Create indices for faster geo-queries and timestamp filtering
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON public.reports (created_at);
CREATE INDEX IF NOT EXISTS idx_reports_report_type ON public.reports (report_type);

-- 3. Row-Level Security (RLS) configuration (Optional but recommended)
-- Enable RLS so we can govern who reads or edits
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Allow all users to select (read) active or all reports
CREATE POLICY "Allow public select of reports" 
ON public.reports 
FOR SELECT 
USING (true);

-- Allow all users to insert reports
CREATE POLICY "Allow public insert of reports" 
ON public.reports 
FOR INSERT 
WITH CHECK (true);
